"""
Django settings for servSegurityCam project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = "django-insecure-+_979@$r=59pra)6g(o&qljbs7d0jn=-g%(a*+8x5p6&#ci(j#"
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '##cg##p$g+j9tax!ssassed#a3cup@1$8obt2_+&k3q+pmu)5%asj6y234qjpkag')


# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = bool(os.environ.get('DJANGO_DEBUG', True))


ALLOWED_HOSTS = ['127.0.0.1']
#ALLOWED_HOSTS = ['http://www.jabali-ti.com/','jabali-ti.com/']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cam.apps.CamConfig",
    "django_celery_results",
    "celery_progress",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "servSegurityCam.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cam.apps.getConfiguraciones",
            ],
        },
    },
]

WSGI_APPLICATION = "servSegurityCam.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
#LANGUAGE_CODE = "es-cl"
TIME_ZONE = "Chile/Continental"
USE_I18N = True
USE_TZ = True

# Redirect to home URL after login (Default redirects to /cam/profile/)
LOGIN_REDIRECT_URL = '/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

#URL WEB

STATIC_URL = "static/"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# CONFIG STORARE URL

WEB_STORAGE_TAKE_PICTURE = 'storage_take_picture'
WEB_STORAGE_PICTURE_MOVE = 'storage_picture_move'
WEB_STORAGE_RECORD = 'storage_record'

STATICFILES_DIRS = [
    (WEB_STORAGE_RECORD, "storage/record/picture/"),
    (WEB_STORAGE_TAKE_PICTURE, "storage/picture/take/"),
    (WEB_STORAGE_PICTURE_MOVE, "storage/move/takePicture/"),
]

#RUTAS OPENCV4.7
DIR_HAARCASCADES = BASE_DIR / 'storage/opencv47/data/haarcascades'
DIR_HAARCASCADES_CUDA= BASE_DIR /'storage/opencv47/data/haarcascades_cuda'
DIR_HOGCASCADES = BASE_DIR / 'storage/opencv47/data/hogcascades'
DIR_LBPCASCADES = BASE_DIR / 'storage/opencv47/data/lbpcascades'

#RUTAS ARCHIVOS DE CONFIGURACION
DIR_CONFIG_FILES = BASE_DIR / 'storage/configFiles'

#RUTAS ARCHIVOS DE IMAGENES
STORAGE_RECORD = BASE_DIR / 'storage/record/picture'
STORAGE_CAM_RECORD = BASE_DIR / 'storage/record/camRecord'
STORAGE_MOVE_DETECTED = BASE_DIR / 'storage/move/'

#RUTAS CAMARA DE MOVIMIENTO
STORAGE_PICTURE_MOVE = BASE_DIR / 'storage/move/takePicture'

STORAGE_TAKE_PICTURE = BASE_DIR / 'storage/picture/take'

STORAGE_TMP = BASE_DIR / 'storage/tmp'


EXTENSION_IMG = '.jpg'
EXTENSION_AVI = '.avi'

DATE_INPUT_FORMATS = ['%Y/%m/%d','%Y%m%d_%H%M%S','%H:%M:%S','%Y/%m/%d %H:%M:%S']

MODELOEIGENFACE = 'modeloEigenFace.xml'
MODELOFISHERFACE = 'modeloFisherFace.xml'
MODELOLBPHFACE = 'modeloLBPHFace.xml'

# atributos camara

SIZESHOWCAM = 500
SCALE_FACTOR = 1.3
MIN_NEIGHBORS = 5

#configuracion CELERY

CELERY_BROKER_URL = 'redis://default:6337821Super@localhost:6379//'
CELERY_ACCEPT_CONTENT= ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'django-db'

#CONFIGURACION WEB WHATSAAP

DIRECCION_URL_WEB_WATSAAP = "http://localhost:3003/lead"

#CONFIGURACION SERVIDOR PARA USO INFORMATIVO
DIRECCION_URL_SERVER = 'http://127.0.0.1:8000/'
